
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcimuovzpnvdgzerkixl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjaW11b3Z6cG52ZGd6ZXJraXhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNDMxMDEsImV4cCI6MjA1NzkxOTEwMX0.GhAqPU8IPgc7SujIVOYCOlppnzukEAV6MCxdxzi0DYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
